name: Build and Push Docker Image

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      NAME: onlinebookstore
      IMAGE_REPO: hemantakumarpati
      IMAGE_URL: hub.docker.com

    steps:
      #  Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      #  Set version tag (BUILD_ID + short commit SHA)
      - name: Set image version
        id: vars
        run: |
          BUILD_ID=${GITHUB_RUN_NUMBER}
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION="${BUILD_ID}-${SHORT_SHA}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=${{ env.NAME }}:$VERSION" >> $GITHUB_ENV

      #  Set up Java (for Maven build)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      #  Build WAR file with Maven
      - name: Build WAR
        run: mvn clean package

      #  Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_REPO/$IMAGE .

      # 7️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_REPO/$IMAGE
