name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      NAME: onlinebookstore
      IMAGE_REPO: hemantakumarpati

    steps:

      # Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set VERSION (BUILD_ID + short SHA)
      - name: Set image version
        id: vars
        run: |
          BUILD_ID=${GITHUB_RUN_NUMBER}
          SHORT_SHA=${GITHUB_SHA::7}
          VERSION="${BUILD_ID}-${SHORT_SHA}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=${{ env.NAME }}:$VERSION" >> $GITHUB_ENV

      # Install Java (required for Maven)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Install Maven (needed for mvn package)
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      # Build WAR file
      - name: Build WAR
        run: mvn clean package

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image 
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_REPO/$IMAGE .

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push $IMAGE_REPO/$IMAGE
